-- Generated by nwg-displays on 2026-07-14 at 16:13:10. Do not edit manually.

hl.monitor({
    output = "DP-2",
    mode = "2560x1440@100.0",
    position = "2560x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-3",
    mode = "2560x1440@100.0",
    position = "7680x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-4",
    mode = "2560x1440@100.0",
    position = "5120x0",
    scale = 1.0
})
